export const TYPEORM_TOKENS = {
    USER_REPOSITORY: Symbol.for('USER_REPOSITORY'),
    ORDER_REPOSITORY: Symbol.for('ORDER_REPOSITORY'),
    PRODUCT_REPOSITORY : Symbol.for('PRODUCT_REPOSITORY')
} as const;
